CREATE SCHEMA IF NOT EXISTS orders;
CREATE SCHEMA IF NOT EXISTS products;

CREATE TABLE IF NOT EXISTS orders.orders (
    id VARCHAR(36) PRIMARY KEY,
    status VARCHAR(20) NOT NULL,
    items TEXT,
    total_amount DECIMAL(10,2),
    customer_id VARCHAR(50),
    tracking_number VARCHAR(100),
    cancel_reason VARCHAR(500),
    version INT NOT NULL DEFAULT 0,
    create_at TIMESTAMP,
    update_at TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS products.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    stock INT NOT NULL,
    version INT NOT NULL DEFAULT 0,
    create_at TIMESTAMP,
    update_at TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);
