-- ============================================================================
-- ID 策略说明：
--   orders  — UUID（业务主键，分布式友好，对应 common-pg UUIDTypeHandler）
--   products — BIGINT IDENTITY（自增，单库简单场景，对应 MyBatis-Plus id-type: auto）
--   两者刻意不同，示范两种主流 ID 策略的共存方式。
-- create_at / update_at 无默认值：由 BasicAutoFillHandler 在应用层填充（非 DB 触发器）。
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS orders;
CREATE SCHEMA IF NOT EXISTS products;

CREATE TABLE IF NOT EXISTS orders.orders (
    id VARCHAR(36) PRIMARY KEY,
    status VARCHAR(20) NOT NULL,
    items TEXT,
    total_amount DECIMAL(10,2),
    customer_id VARCHAR(50),
    tracking_number VARCHAR(100),
    cancel_reason VARCHAR(500),
    version INT NOT NULL DEFAULT 0,
    create_at TIMESTAMP,
    update_at TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    is_delete BOOLEAN NOT NULL DEFAULT FALSE
);

-- 高频查询索引
CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON orders.orders (customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders.orders (status);

CREATE TABLE IF NOT EXISTS products.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    stock INT NOT NULL,
    version INT NOT NULL DEFAULT 0,
    create_at TIMESTAMP,
    update_at TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    is_delete BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_products_name ON products.products (name);
