-- fixture 教学形状（test-tree 豁免区：真实业务名合法，非服务形状——服务形状权威在 db-migration）
-- 本卷由 PgTestSupport 每 JVM 复位时在 currentSchema=integration_test 的会话内执行；
-- 表名一律不带 schema 限定，可见性由数据源 currentSchema 裁决（master=integration_test 有表、
-- second=integration_test_vacant 空 schema → 路由脱靶教例的真实性来源，TC-9 框架轨）。
CREATE TABLE IF NOT EXISTS orders (
    id VARCHAR(36) PRIMARY KEY,
    status VARCHAR(20) NOT NULL,
    items TEXT,
    total_amount DECIMAL(10,2),
    customer_id VARCHAR(50),
    tracking_number VARCHAR(100),
    cancel_reason VARCHAR(500),
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    stock INT NOT NULL,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);
